on: [ push ]
name: Continuous Integration

# Inspired by Lighthouse's CI
# https://github.com/LBPUnion/project-lighthouse/blob/main/.github/workflows/ci.yml

jobs:
  test:
    name: Build for ${{ matrix.os.name }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix: 
        os:
          - { name: Windows, platform: win-x64 }
          - { name: Linux, platform: linux-x64 }
          - { name: MacOS, platform: osx-x64 }
    steps:
      - name: Cancel previous runs of this workflow
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
          
      - name: Compile
        run: dotnet publish -c ${{ matrix.os.name }} -r ${{ matrix.os.platform }}
        
      - uses: actions/upload-artifact@v2
        with:
          name: UnionPatcher-${{ matrix.os.name }}
          path: ${{ github.workspace }}/UnionPatcher.Gui.${{ matrix.os.name }}/bin